language: python
python:
- '3.6'
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- make
branches:
  except:
  - master
before_install:
- sudo apt-get install -y poppler-utils
- openssl aes-256-cbc -K $encrypted_2078d2dbf730_key -iv $encrypted_2078d2dbf730_iv -in fixtures.tar.enc -out fixtures.tar -d
- tar xvf fixtures.tar
